os: linux
dist: xenial
services: docker
language: minimal
install: skip
addons:
  apt:
    packages:
    - pass
script: "./travis.sh -b"
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis.sh -p"
  on:
    repo: umarcor/dbhi
    branch: docker
