os: linux
dist: xenial
services: docker
language: minimal
install: skip
#addons:
#  apt:
#    packages:
#    - pass

stages:
  - test
  - ext
  - publish

jobs:
  include:
    - &build
      env:
        - TARGET_ARCHS=aarch64
        - IMAGES="main mambo"
      before_script: docker run --rm --privileged aptman/qus -s -- -r ALL -p $TARGET_ARCHS
      script: ./travis.sh -b $IMAGES
      deploy: &script
        provider: script
        skip_cleanup: true
        script: ./travis.sh -p $IMAGES
        on:
          repo: dbhi/docker
          branch: master
    - <<: *build
      env:
        - TARGET_ARCHS=amd64
        - IMAGES=ALL
      before_script: skip
    - <<: *build
      env:
        - TARGET_ARCHS=arm
        - IMAGES="main mambo"
    - stage: ext
      <<: *build
      env:
        - TARGET_ARCHS=aarch64
        - IMAGES="dr"
    - stage: ext
      <<: *build
      env:
        - TARGET_ARCHS=arm
        - IMAGES="dr"
    - stage: ext
      <<: *build
      env:
        - TARGET_ARCHS=aarch64
        - IMAGES="gtkwave"
    - stage: ext
      <<: *build
      env:
        - TARGET_ARCHS=arm
        - IMAGES="gtkwave"
    - stage: publish
      env: MANIFESTS=
      script: skip
      deploy:
        <<: *script
        script: ./travis.sh -m
