name: 'push'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

env:
    DOCKER_BUILDKIT: '1'

jobs:


  main:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { arch: amd64, qarch: ''}
        - { arch: arm,   qarch: arm}
        - { arch: arm64, qarch: aarch64}
    runs-on: ubuntu-latest
    env:
      TGT_ARCHS: ${{ matrix.arch }}
    name: '${{ matrix.arch }} | main'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '⚙️ Setup qus'
      if: ${{ matrix.qarch }} != ''
      run: |
        docker run --rm --privileged aptman/qus -- -r
        docker run --rm --privileged aptman/qus -s -- -p ${{ matrix.qarch }}

    - name: '🚧 Run job'
      run: ./run.sh -b main

    - name: '⛴️ Login to docker.io'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: '🚀 Push'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      run: ./run.sh -p main


  common:
    needs: main
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { arch: amd64, qarch: ''}
        - { arch: arm,   qarch: arm}
        - { arch: arm64, qarch: aarch64}
        img:
        - dr
        - cosim
    runs-on: ubuntu-latest
    env:
      TGT_ARCHS: ${{ matrix.platform.arch }}
    name: '${{ matrix.platform.arch }} | ${{ matrix.img }}'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '⚙️ Setup qus'
      if: ${{ matrix.qarch }} != ''
      run: |
        docker run --rm --privileged aptman/qus -- -r
        docker run --rm --privileged aptman/qus -s -- -p ${{ matrix.platform.qarch }}

    - name: '🚧 Run job'
      run: ./run.sh -b ${{ matrix.img }}

    - name: '⛴️ Login to docker.io'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: '🚀 Push'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      run: ./run.sh -p ${{ matrix.img }}


  amd64:
    needs: main
    strategy:
      fail-fast: false
      matrix:
        img:
        - gRPC
        - spinalhdl
    runs-on: ubuntu-latest
    env:
      TGT_ARCHS: amd64
    name: 'amd64 | ${{ matrix.img }}'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '🚧 Run job'
      run: ./run.sh -b ${{ matrix.img }}

    - name: '⛴️ Login to docker.io'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: '🚀 Push'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      run: ./run.sh -p ${{ matrix.img }}


  mambo:
    needs: main
    strategy:
      fail-fast: false
      matrix:
        arch:
        - arm
        - aarch64
    runs-on: ubuntu-latest
    env:
      TGT_ARCHS: ${{ matrix.arch }}
    name: '${{ matrix.arch }} | mambo'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '⚙️ Setup qus for ${{ matrix.arch }}'
      run: |
        docker run --rm --privileged aptman/qus -- -r
        docker run --rm --privileged aptman/qus -s -- -p ${{ matrix.arch }}

    - name: '🚧 Run job'
      run: ./run.sh -b mambo

    - name: '⛴️ Login to docker.io'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: '🚀 Push'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      run: ./run.sh -p mambo


  octave:
    needs: common
    strategy:
      fail-fast: false
      matrix:
        include:
        - { arch: amd64, qarch: ''}
        - { arch: arm,   qarch: arm}
        - { arch: arm64, qarch: aarch64}
    runs-on: ubuntu-latest
    env:
      TGT_ARCHS: ${{ matrix.arch }}
    name: '${{ matrix.arch }} | octave'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '⚙️ Setup qus for ${{ matrix.qarch }}'
      if: ${{ matrix.qarch }} != ''
      run: |
        docker run --rm --privileged aptman/qus -- -r
        docker run --rm --privileged aptman/qus -s -- -p ${{ matrix.qarch }}

    - name: '🚧 Run job'
      run: ./run.sh -b octave

    - name: '⛴️ Login to docker.io'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: '🚀 Push'
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
      run: ./run.sh -p octave


  manifests:
    if: github.event_name != 'pull_request' && github.repository == 'dbhi/containers'
    needs:
    - amd64
    - mambo
    - octave
    runs-on: ubuntu-latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '⛴️ Login to docker.io'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: '🛰️ Update manifests'
      run: ./run.sh -m

# FIXIT: ensure that branches different from 'master' do not trigger deploy steps!
